---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-executables-have-shebangs
      # TODO: fix Helm templates
      #- id: check-yaml
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: check-ast

  # TODO: config it better
#  - repo: https://github.com/hadolint/hadolint
#    rev: v2.12.0
#    hooks:
#      - id: hadolint-docker

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1  # Ruff version to use.
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]
      # Run the formatter.
      - id: ruff-format
