services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: bitnami/redis:8.0.2
    container_name: 'redis'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    image: postgres:17.5-bookworm
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password

  moto:
    image: motoserver/moto:5.1.6
    ports:
      - "3000:3000"
    environment:
      - MOTO_PORT=3000

