services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: bitnami/redis:8.0.2
    container_name: 'redis'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    image: postgres:17.5-bookworm
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password

  minio:
    image: bitnami/minio:2025.5.24-debian-12-r7
    container_name: 'minio'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: test_access_key
      MINIO_ROOT_PASSWORD: test_secret_key

  createbuckets:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    container_name: 'createbuckets'
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 test_access_key test_secret_key;
      /usr/bin/mc mb dockerminio/test-bucket;
      exit 0;
      "
