-- Insert into the cocktails table
INSERT INTO cocktails (id, name, description, rating, recipe, alcohol_content, created_at, updated_at) VALUES
(gen_random_uuid(), 'Margarita', 'A refreshing cocktail with tequila, lime, and Cointreau.', 4.5, '1.5 oz Tequila\n1 oz Lime juice\n0.5 oz Cointreau\nSalt rim\nShake with ice, strain into a salt-rimmed glass.', 40, NOW(), NOW()),
(gen_random_uuid(), 'Old Fashioned', 'A classic cocktail with bourbon, sugar, and bitters.', 4.8, '2 oz Bourbon\n1 sugar cube\n2 dashes Angostura bitters\nOrange twist\nMuddle sugar and bitters, add bourbon and ice, stir.', 45, NOW(), NOW()),
(gen_random_uuid(),  'Clover Club', 'A classic cocktail with gin, lemon, raspberry syrup, and egg white.', 4.6, '1.5 oz Gin\n0.75 oz Lemon juice\n0.75 oz Raspberry syrup\n1 Egg white\nShake all ingredients with ice, strain into a cocktail glass.', 20, NOW(), NOW()),
(gen_random_uuid(), 'White Russian', 'A creamy cocktail with vodka, coffee liqueur, and cream.', 4.3, '2 oz Vodka\n1 oz Coffee liqueur\n1 oz Cream\nBuild in an old-fashioned glass filled with ice, stir gently.', 24, NOW(), NOW()),
(gen_random_uuid(), 'Sex on the Beach', 'A fruity cocktail with vodka, peach schnapps, cranberry juice, and orange juice.', 4.2, '1.5 oz Vodka\n0.5 oz Peach schnapps\n2 oz Cranberry juice\n2 oz Orange juice\nBuild all ingredients in a highball glass filled with ice, stir.', 18, NOW(), NOW()),
(gen_random_uuid(), 'Arnaud', 'A classic cocktail with cognac, Dubonnet Rouge, and Angostura bitters.', 4.7, '2 oz Cognac\n1 oz Dubonnet Rouge\n2 dashes Angostura bitters\nStir all ingredients with ice and strain into a cocktail glass.', 30, NOW(), NOW()),
(gen_random_uuid(), 'Gin & Tonic', 'A refreshing cocktail with gin and tonic water.', 4.5, '2 oz Gin\n4 oz Tonic water\nBuild all ingredients in a highball glass filled with ice, stir gently, garnish with a lime wedge.', 10, NOW(), NOW()),
(gen_random_uuid(), 'Enzoni', 'A modern cocktail with gin, Campari, grapes, lemon juice, and simple syrup.', 4.4, '1 oz Gin\n1 oz Campari\n5 Green grapes\n0.5 oz Lemon juice\n0.5 oz Simple syrup\nMuddle grapes in a shaker, add other ingredients and ice, shake, and strain into a rocks glass.', 22, NOW(), NOW()),
(gen_random_uuid(), 'Velvet Hammer', 'A creamy cocktail with vodka, orange liqueur, and cream.', 4.3, '1 oz Vodka\n1 oz Orange liqueur\n1 oz Cream\nShake all ingredients with ice and strain into a cocktail glass.', 24, NOW(), NOW()),
(gen_random_uuid(), 'Grasshopper', 'A minty creamy cocktail with green crème de menthe, white crème de cacao, and cream.', 4.2, '1 oz Green crème de menthe\n1 oz White crème de cacao\n1 oz Cream\nShake all ingredients with ice and strain into a cocktail glass.', 15, NOW(), NOW()),
(gen_random_uuid(), 'Golden Cadillac', 'A creamy cocktail with Galliano, white crème de cacao, and cream.', 4.4, '1 oz Galliano\n1 oz White crème de cacao\n1 oz Cream\nShake all ingredients with ice and strain into a cocktail glass.', 18, NOW(), NOW()),
(gen_random_uuid(), 'Intro to Aperol', 'A light and refreshing cocktail with Aperol, gin, and grapefruit juice.', 4.5, '1 oz Aperol\n1 oz Gin\n1 oz Grapefruit juice\nShake all ingredients with ice and strain into a cocktail glass.', 15, NOW(), NOW()),
(gen_random_uuid(), 'Moscow Mule', 'A spicy and refreshing cocktail with vodka, lime juice, and ginger beer.', 4.6, '2 oz Vodka\n0.5 oz Lime juice\n4 oz Ginger beer\nBuild in a copper mug filled with ice, stir gently, garnish with a lime wedge.', 10, NOW(), NOW()),
(gen_random_uuid(), 'Moonlight Shine', 'A cocktail with moonshine, blue curaçao, and lemon-lime soda.', 4.3, '1.5 oz Moonshine\n0.5 oz Blue curaçao\n4 oz Lemon-lime soda\nBuild in a highball glass filled with ice, stir gently.', 25, NOW(), NOW()),
(gen_random_uuid(), 'Blue Hawai', 'A tropical cocktail with rum, blue curaçao, pineapple juice, and coconut cream.', 4.7, '1 oz Rum\n0.5 oz Blue curaçao\n3 oz Pineapple juice\n1 oz Coconut cream\nShake all ingredients with ice and strain into a hurricane glass.', 18, NOW(), NOW()),
(gen_random_uuid(), 'Mojito', 'A refreshing cocktail with rum, mint, lime, and soda water.', 4.7, '2 oz White rum\n1 oz Lime juice\n2 tsp Sugar\nMint leaves\nSoda water\nMuddle mint and sugar, add rum and lime juice, top with soda water.', 20, NOW(), NOW()),
(gen_random_uuid(), 'Jagermonster (Jpz. E 100)', 'A cocktail with Jägermeister and orange juice.', 4.3, '1.5 oz Jägermeister\n3 oz Orange juice\nShake with ice and strain into a cocktail glass.', 35, NOW(), NOW()),
(gen_random_uuid(), 'Wild Sour', 'A cocktail with Jägermeister, orange juice, and egg white.', 4.5, '1.5 oz Jägermeister\n1 oz Orange juice\n1 Egg white\nShake all ingredients with ice, strain into a cocktail glass.', 35, NOW(), NOW()),
(gen_random_uuid(), 'Orgasm', 'A creamy cocktail with coffee liqueur, amaretto, and Irish cream.', 4.4, '1 oz Coffee liqueur\n1 oz Amaretto\n1 oz Irish cream\nShake with ice and strain into a cocktail glass.', 25, NOW(), NOW()),
(gen_random_uuid(), 'Singapore Sling', 'A complex cocktail with gin, cherry brandy, and pineapple juice.', 4.7, '1 oz Gin\n0.5 oz Cherry brandy\n4 oz Pineapple juice\n0.25 oz Cointreau\n0.25 oz Benedictine\n0.5 oz Lime juice\n1 dash Angostura bitters\nShake with ice and strain into a highball glass.', 25, NOW(), NOW()),
(gen_random_uuid(), 'Screwdriver Enhanced', 'A Screwdriver with an added twist of Galliano.', 4.4, '1.5 oz Vodka\n3 oz Orange juice\n0.5 oz Galliano\nShake with ice and strain into a highball glass.', 30, NOW(), NOW()),
(gen_random_uuid(), 'Japanese Slippers', 'A refreshing cocktail with Midori, Cointreau, and lemon juice.', 4.5, '1 oz Midori\n1 oz Cointreau\n1 oz Lemon juice\nShake with ice and strain into a cocktail glass.', 15, NOW(), NOW()),
(gen_random_uuid(), 'Lemon Pie', 'A dessert cocktail with vanilla vodka, lemon juice, and cream.', 4.2, '1 oz Vanilla vodka\n1 oz Lemon juice\n1 oz Cream\nShake with ice and strain into a cocktail glass, garnish with a lemon twist.', 20, NOW(), NOW()),
(gen_random_uuid(), 'Pornstar Martini', 'A modern classic with vanilla vodka, passion fruit liqueur, and prosecco.', 4.8, '1.5 oz Vanilla vodka\n1 oz Passion fruit liqueur\n0.5 oz Lime juice\n0.5 oz Vanilla syrup\n1 shot Prosecco on the side\nShake with ice and strain into a cocktail glass.', 20, NOW(), NOW()),
(gen_random_uuid(), 'Bramble', 'A refreshing cocktail with gin, lemon juice, and blackberry liqueur.', 4.6, '1.5 oz Gin\n1 oz Lemon juice\n0.5 oz Simple syrup\n0.5 oz Blackberry liqueur\nShake gin, lemon juice, and syrup with ice and strain into a rocks glass, drizzle blackberry liqueur on top.', 18, NOW(), NOW()),
(gen_random_uuid(), 'Naked Lady', 'A classic cocktail with gin, apricot brandy, and lemon juice.', 4.4, '1.5 oz Gin\n0.5 oz Apricot brandy\n0.5 oz Lemon juice\nShake with ice and strain into a cocktail glass.', 20, NOW(), NOW()),
(gen_random_uuid(), 'Midori Sour', 'A sweet and sour cocktail with Midori and lemon juice.', 4.5, '1.5 oz Midori\n1 oz Lemon juice\n0.5 oz Simple syrup\nShake with ice and strain into a cocktail glass.', 15, NOW(), NOW()),
(gen_random_uuid(), 'Angel Face', 'A classic cocktail with gin, apricot brandy, and apple brandy.', 4.7, '1 oz Gin\n1 oz Apricot brandy\n1 oz Apple brandy\nShake with ice and strain into a cocktail glass.', 25, NOW(), NOW());

-- Insert into the images table
INSERT INTO images (id, cocktail_id, image_url, is_thumbnail, created_at, updated_at) VALUES
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Margarita'), 'https://chibisafe.eucalytics.uk/enR2STnIYdoY.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Old Fashioned'), 'https://chibisafe.eucalytics.uk/RJyWtZFjk0gt.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Mojito'), 'https://chibisafe.eucalytics.uk/LHQJxpCZF1IL.webp', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Clover Club'), 'https://chibisafe.eucalytics.uk/6nK6H1RBQnKI.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'White Russian'), 'https://chibisafe.eucalytics.uk/bgeGk05hLFDt.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Sex on the Beach'), 'https://chibisafe.eucalytics.uk/JN6JFIRYSgvN.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Arnaud'), 'https://chibisafe.eucalytics.uk/rRWFTManaYhy.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Gin & Tonic'), 'https://chibisafe.eucalytics.uk/yHquYNcLykks.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Enzoni'), 'https://chibisafe.eucalytics.uk/rlp0gGB6Qtm1.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Velvet Hammer'), 'https://chibisafe.eucalytics.uk/ILttQ8ZavZsE.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Grasshopper'), 'https://chibisafe.eucalytics.uk/zrs0YGRAPCoG.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Golden Cadillac'), 'https://chibisafe.eucalytics.uk/orZK6amqFhQQ.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Intro to Aperol'), 'https://chibisafe.eucalytics.uk/ZdzJFfG0sEcT.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Moscow Mule'), 'https://chibisafe.eucalytics.uk/33LwHZLTZZxI.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Moonlight Shine'), '', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Blue Hawai'), 'https://chibisafe.eucalytics.uk/hGOcw3KXOy2t.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Jagermonster (Jpz. E 100)'), 'https://your-image-url-here/jagermonster.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Wild Sour'), 'https://your-image-url-here/wildsour.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Orgasm'), 'https://your-image-url-here/orgasm.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Singapore Sling'), 'https://your-image-url-here/singaporesling.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Screwdriver Enhanced'), 'https://your-image-url-here/screwdriverenhanced.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Japanese Slippers'), 'https://your-image-url-here/japaneseslippers.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Lemon Pie'), 'https://your-image-url-here/lemonpie.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Pornstar Martini'), 'https://your-image-url-here/pornstarmartini.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Bramble'), 'https://your-image-url-here/bramble.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Naked Lady'), 'https://your-image-url-here/nakedlady.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Midori Sour'), 'https://your-image-url-here/midorisour.jpg', TRUE, NOW(), NOW()),
(gen_random_uuid(), (SELECT id FROM cocktails WHERE name = 'Angel Face'), 'https://your-image-url-here/angelface.jpg', TRUE, NOW(), NOW());



-- Insert into the labels table
INSERT INTO labels (id, name, created_at, updated_at) VALUES
(gen_random_uuid(), 'Tequila', NOW(), NOW()),
(gen_random_uuid(), 'Bourbon', NOW(), NOW()),
(gen_random_uuid(), 'Rum', NOW(), NOW()),
(gen_random_uuid(), 'Citrus', NOW(), NOW()),
(gen_random_uuid(), 'Classic', NOW(), NOW()),
(gen_random_uuid(), 'Gin', NOW(), NOW()),
(gen_random_uuid(), 'Vodka', NOW(), NOW()),
(gen_random_uuid(), 'Peach', NOW(), NOW()),
(gen_random_uuid(), 'Cognac', NOW(), NOW()),
(gen_random_uuid(), 'Bitter', NOW(), NOW()),
(gen_random_uuid(), 'Cream', NOW(), NOW()),
(gen_random_uuid(), 'Mint', NOW(), NOW()),
(gen_random_uuid(), 'Tropical', NOW(), NOW()),
(gen_random_uuid(), 'Aperitif', NOW(), NOW());


-- Insert into the cocktail_labels table
INSERT INTO cocktail_labels (cocktail_id, label_id, created_at, updated_at) VALUES
((SELECT id FROM cocktails WHERE name = 'Margarita'), (SELECT id FROM labels WHERE name = 'Tequila'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Margarita'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Old Fashioned'), (SELECT id FROM labels WHERE name = 'Bourbon'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Old Fashioned'), (SELECT id FROM labels WHERE name = 'Classic'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Mojito'), (SELECT id FROM labels WHERE name = 'Rum'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Mojito'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Clover Club'), (SELECT id FROM labels WHERE name = 'Gin'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'White Russian'), (SELECT id FROM labels WHERE name = 'Vodka'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Sex on the Beach'), (SELECT id FROM labels WHERE name = 'Vodka'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Sex on the Beach'), (SELECT id FROM labels WHERE name = 'Peach'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Arnaud'), (SELECT id FROM labels WHERE name = 'Cognac'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Gin & Tonic'), (SELECT id FROM labels WHERE name = 'Gin'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Enzoni'), (SELECT id FROM labels WHERE name = 'Gin'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Enzoni'), (SELECT id FROM labels WHERE name = 'Bitter'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Velvet Hammer'), (SELECT id FROM labels WHERE name = 'Vodka'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Velvet Hammer'), (SELECT id FROM labels WHERE name = 'Cream'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Grasshopper'), (SELECT id FROM labels WHERE name = 'Cream'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Grasshopper'), (SELECT id FROM labels WHERE name = 'Mint'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Golden Cadillac'), (SELECT id FROM labels WHERE name = 'Cream'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Golden Cadillac'), (SELECT id FROM labels WHERE name = 'Tropical'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Intro to Aperol'), (SELECT id FROM labels WHERE name = 'Aperitif'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Moscow Mule'), (SELECT id FROM labels WHERE name = 'Vodka'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Moonlight Shine'), (SELECT id FROM labels WHERE name = 'Tropical'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Blue Hawai'), (SELECT id FROM labels WHERE name = 'Tropical'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Jagermonster (Jpz. E 100)'), (SELECT id FROM labels WHERE name = 'Tropical'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Jagermonster (Jpz. E 100)'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Wild Sour'), (SELECT id FROM labels WHERE name = 'Tropical'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Wild Sour'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Orgasm'), (SELECT id FROM labels WHERE name = 'Cream'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Singapore Sling'), (SELECT id FROM labels WHERE name = 'Gin'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Singapore Sling'), (SELECT id FROM labels WHERE name = 'Tropical'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Screwdriver Enhanced'), (SELECT id FROM labels WHERE name = 'Vodka'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Screwdriver Enhanced'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Japanese Slippers'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Lemon Pie'), (SELECT id FROM labels WHERE name = 'Cream'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Pornstar Martini'), (SELECT id FROM labels WHERE name = 'Tropical'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Bramble'), (SELECT id FROM labels WHERE name = 'Gin'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Bramble'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Naked Lady'), (SELECT id FROM labels WHERE name = 'Gin'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Naked Lady'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Midori Sour'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Angel Face'), (SELECT id FROM labels WHERE name = 'Gin'), NOW(), NOW()),
((SELECT id FROM cocktails WHERE name = 'Angel Face'), (SELECT id FROM labels WHERE name = 'Citrus'), NOW(), NOW());
