name: test
on: [ push, pull_request ]

jobs:
  uv-setup:
    name: "tests"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.5-bookworm
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: bitnami/redis:8.0.2
        env:
          ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 6379:6379

      mailhog:
        image: mailhog/mailhog:v1.0.1
        ports:
          - 1025:1025
          - 8025:8025

      minio:
        image: bitnami/minio:2025.5.24-debian-12-r7
        env:
          MINIO_ROOT_USER: test_access_key
          MINIO_ROOT_PASSWORD: test_secret_key
          MINIO_DEFAULT_BUCKETS: "assets-test"
        ports:
          - 9000:9000          # API
          - 9001:9001          # (opt) web-console

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6.3.1

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests
        run: |
          uv run pytest
