"""refactor(Users): add customer_type and mailing

Revision ID: 059e5d6c62fe
Revises: 35abf5288352
Create Date: 2025-06-11 18:40:32.664488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059e5d6c62fe'
down_revision: Union[str, None] = '35abf5288352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'customer_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'mailing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mailing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'customer_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
