"""upd balance

Revision ID: 073f2af8b3ac
Revises: bee7f8de8bac
Create Date: 2025-08-23 17:20:43.376951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073f2af8b3ac'
down_revision: Union[str, None] = 'bee7f8de8bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance_rub',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance_rub',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
