"""refactor(product): remove sub_category_slug

Revision ID: 0c288ad36040
Revises: 5c83a73dce7b
Create Date: 2025-05-24 20:45:27.438153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c288ad36040'
down_revision: Union[str, None] = '5c83a73dce7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sub_category_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sub_category_slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
