"""user: drop counterparty

Revision ID: 17576ba06e30
Revises: a9b33566ba3f
Create Date: 2025-07-26 10:21:16.255253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17576ba06e30'
down_revision: Union[str, None] = 'a9b33566ba3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waybills', 'counterparty_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybills', sa.Column('counterparty_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
