"""add email do order

Revision ID: 20b5a18cbc95
Revises: 827e7e03a057
Create Date: 2025-12-27 11:57:38.674041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b5a18cbc95'
down_revision: Union[str, None] = '827e7e03a057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###
