"""categories: remove seo_name column

Revision ID: 2724533d218d
Revises: 71913273cbc3
Create Date: 2025-04-30 21:52:53.927780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2724533d218d'
down_revision: Union[str, None] = '71913273cbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'seo_name')
    op.drop_column('sub_categories', 'seo_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_categories', sa.Column('seo_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('seo_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
