"""Add cart_id to cart_offers

Revision ID: 32d814914828
Revises: dd0e52adb02b
Create Date: 2025-07-04 22:03:44.488297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d814914828'
down_revision: Union[str, None] = 'dd0e52adb02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_offers', sa.Column('cart_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('fk_cart_offers_user_id_users'), 'cart_offers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cart_offers_cart_id_carts'), 'cart_offers', 'carts', ['cart_id'], ['id'])
    op.drop_column('cart_offers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_offers', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_cart_offers_cart_id_carts'), 'cart_offers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cart_offers_user_id_users'), 'cart_offers', 'users', ['user_id'], ['id'])
    op.drop_column('cart_offers', 'cart_id')
    # ### end Alembic commands ###
