"""refactor(Users): add customer_type and mailing

Revision ID: 35abf5288352
Revises: 709bd83c8a6f
Create Date: 2025-06-11 18:38:07.737152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35abf5288352'
down_revision: Union[str, None] = '709bd83c8a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customer_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mailing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mailing')
    op.drop_column('users', 'customer_type')
    # ### end Alembic commands ###
