"""refactor(waybill): change name of column

Revision ID: 417ec20c1d0f
Revises: 6d020132622d
Create Date: 2025-05-29 22:08:02.511956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417ec20c1d0f'
down_revision: Union[str, None] = '6d020132622d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('waybill_type', sa.String(), nullable=False))
    op.drop_column('stock_movements', 'type')
    op.add_column('waybills', sa.Column('waybill_type', sa.String(), nullable=False))
    op.drop_column('waybills', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybills', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('waybills', 'waybill_type')
    op.add_column('stock_movements', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('stock_movements', 'waybill_type')
    # ### end Alembic commands ###
