"""refactor orders

Revision ID: 4f368117b1f1
Revises: 370c8d5aea37
Create Date: 2025-07-17 18:24:19.610669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f368117b1f1'
down_revision: Union[str, None] = '370c8d5aea37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('NEW', 'IN_PROGRESS', 'SHIPPING', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('NEW', 'IN_PROGRESS', 'SHIPPING', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
