"""refactor(subcategory): remove category_slug

Revision ID: 5c83a73dce7b
Revises: 9d6164e07ac4
Create Date: 2025-05-23 14:46:33.121915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c83a73dce7b'
down_revision: Union[str, None] = '9d6164e07ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_categories', 'category_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_categories', sa.Column('category_slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
