"""add currencies

Revision ID: 6c0af3710fce
Revises: 854d349fc48f
Create Date: 2025-10-26 18:04:57.683991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0af3710fce'
down_revision: Union[str, None] = '854d349fc48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance_usd', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('users', sa.Column('balance_eur', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('users', sa.Column('balance_try', sa.Numeric(precision=12, scale=4), nullable=True))
    op.alter_column('users', 'balance_rub',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance_rub',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'balance_try')
    op.drop_column('users', 'balance_eur')
    op.drop_column('users', 'balance_usd')
    # ### end Alembic commands ###
