"""refactor(Offers): move address_id to offer from product

Revision ID: 709bd83c8a6f
Revises: e06874c40e37
Create Date: 2025-06-10 18:52:18.866792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709bd83c8a6f'
down_revision: Union[str, None] = 'e06874c40e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('address_id', sa.String(), nullable=True))
    op.drop_column('products', 'address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('address_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('offers', 'address_id')
    # ### end Alembic commands ###
