"""remove addresses

Revision ID: 827e7e03a057
Revises: bd0025b33089
Create Date: 2025-12-26 21:30:44.128880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '827e7e03a057'
down_revision: Union[str, None] = 'bd0025b33089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('addresses')
    # op.drop_table('carts')
    # op.drop_table('cart_offers')
    op.add_column('orders', sa.Column('country', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('street', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('house', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_company', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_method', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=False))
    # op.drop_constraint(op.f('fk_orders_address_id_addresses'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'address_id')
    # op.drop_constraint(op.f('uq_users_clerk_id'), 'users', type_='unique')
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_users_clerk_id'), 'users', ['clerk_id'], postgresql_nulls_not_distinct=False)
    op.add_column('orders', sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_orders_address_id_addresses'), 'orders', 'addresses', ['address_id'], ['id'])
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'last_name')
    op.drop_column('orders', 'first_name')
    op.drop_column('orders', 'shipping_method')
    op.drop_column('orders', 'shipping_company')
    op.drop_column('orders', 'postal_code')
    op.drop_column('orders', 'house')
    op.drop_column('orders', 'street')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'country')
    op.create_table('cart_offers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('offer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_offers_cart_id_carts')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_cart_offers_offer_id_offers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_offers'))
    )
    op.create_table('carts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts'))
    )
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shipping_method', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('shipping_company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    # ### end Alembic commands ###
