"""add user_balance_history

Revision ID: 854d349fc48f
Revises: 918924714c75
Create Date: 2025-10-13 20:37:38.745375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '854d349fc48f'
down_revision: Union[str, None] = '918924714c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_balance_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('waybill_id', sa.UUID(), nullable=True),
    sa.Column('delta', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_balance_history_user_id_users')),
    sa.ForeignKeyConstraint(['waybill_id'], ['waybills.id'], name=op.f('fk_user_balance_history_waybill_id_waybills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_balance_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_balance_history')
    # ### end Alembic commands ###
