"""refactor: DB structure

Revision ID: 9d6164e07ac4
Revises: 2724533d218d
Create Date: 2025-05-14 18:21:18.808094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d6164e07ac4'
down_revision: Union[str, None] = '2724533d218d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('offer_bitrix_id', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('manufacturer_number', sa.String(), nullable=True),
    sa.Column('internal_description', sa.Text(), nullable=True),
    sa.Column('price_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('super_wholesale_price_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_offers_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.drop_index('idx_products_embedding', table_name='products', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'super_wholesale_price_rub')
    op.drop_column('products', 'embedding')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'manufacturer_number')
    op.drop_column('products', 'seo_name')
    op.drop_column('products', 'price_rub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_rub', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('seo_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('manufacturer_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('super_wholesale_price_rub', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('idx_products_embedding', 'products', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_table('offers')
    # ### end Alembic commands ###
