"""waybill: add note

Revision ID: a577e5a38788
Revises: 72a38b052d6d
Create Date: 2025-07-20 20:56:43.553897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a577e5a38788'
down_revision: Union[str, None] = '72a38b052d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybills', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waybills', 'note')
    # ### end Alembic commands ###
