"""add customer for waybill

Revision ID: a9b33566ba3f
Revises: fc4cd58848aa
Create Date: 2025-07-24 15:16:05.681744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b33566ba3f'
down_revision: Union[str, None] = 'fc4cd58848aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybills', sa.Column('author_id', sa.UUID(), nullable=False))
    op.add_column('waybills', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('fk_waybills_user_id_users'), 'waybills', type_='foreignkey')
    op.create_foreign_key(op.f('fk_waybills_customer_id_users'), 'waybills', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('fk_waybills_author_id_users'), 'waybills', 'users', ['author_id'], ['id'])
    op.drop_column('waybills', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybills', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_waybills_author_id_users'), 'waybills', type_='foreignkey')
    op.drop_constraint(op.f('fk_waybills_customer_id_users'), 'waybills', type_='foreignkey')
    op.create_foreign_key(op.f('fk_waybills_user_id_users'), 'waybills', 'users', ['user_id'], ['id'])
    op.drop_column('waybills', 'customer_id')
    op.drop_column('waybills', 'author_id')
    # ### end Alembic commands ###
