"""upd type for currencies

Revision ID: bd0025b33089
Revises: 6c0af3710fce
Create Date: 2025-10-26 18:13:07.575786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0025b33089'
down_revision: Union[str, None] = '6c0af3710fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_balance_history', 'delta',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_balance_history', 'balance_before',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_balance_history', 'balance_after',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('users', 'balance_rub',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('users', 'balance_usd',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('users', 'balance_eur',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('users', 'balance_try',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.BigInteger(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance_try',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('users', 'balance_eur',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('users', 'balance_usd',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('users', 'balance_rub',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('user_balance_history', 'balance_after',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('user_balance_history', 'balance_before',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('user_balance_history', 'delta',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
