"""refactor address

Revision ID: c1eb870b0d0e
Revises: 32d814914828
Create Date: 2025-07-08 21:02:43.234976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1eb870b0d0e'
down_revision: Union[str, None] = '32d814914828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('addresses', sa.Column('last_name', sa.String(), nullable=False))
    op.alter_column('addresses', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('addresses', 'full_name')
    op.drop_column('addresses', 'country')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('addresses', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('addresses', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('addresses', 'last_name')
    op.drop_column('addresses', 'first_name')
    # ### end Alembic commands ###
