"""add order cart_offer order_offer tables

Revision ID: c942c879d3e3
Revises: ce5683ad444d
Create Date: 2025-07-04 16:41:09.404808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c942c879d3e3'
down_revision: Union[str, None] = 'ce5683ad444d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'SHIPPING', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_orders_address_id_addresses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('cart_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_cart_offers_offer_id_offers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cart_offers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_offers'))
    )
    op.create_table('order_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('manufacturer_number', sa.String(), nullable=True),
    sa.Column('price_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_order_offers_offer_id_offers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_offers_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_offers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_offers')
    op.drop_table('cart_offers')
    op.drop_table('orders')
    # ### end Alembic commands ###
