"""add address table

Revision ID: ce5683ad444d
Revises: 059e5d6c62fe
Create Date: 2025-06-28 12:22:21.018772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce5683ad444d'
down_revision: Union[str, None] = '059e5d6c62fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('shipping_method', sa.Enum('SELF_PICKUP', 'CARGO', 'OTHER', name='shippingmethod', native_enum=False), nullable=False),
    sa.Column('shipping_company', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('shipping_method', sa.Enum('SELF_PICKUP', 'CARGO', 'OTHER', name='shippingmethod', native_enum=False), nullable=True))
    op.add_column('users', sa.Column('shipping_company', sa.String(), nullable=True))
    op.drop_column('users', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'shipping_company')
    op.drop_column('users', 'shipping_method')
    op.drop_column('users', 'notes')
    op.drop_column('users', 'city')
    op.drop_column('users', 'phone')
    op.drop_table('addresses')
    # ### end Alembic commands ###
