"""add order_id for waybill

Revision ID: e2c6de04ee64
Revises: 17576ba06e30
Create Date: 2025-08-17 15:11:50.221089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c6de04ee64'
down_revision: Union[str, None] = '17576ba06e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybills', sa.Column('order_id', sa.UUID(), nullable=True))
    op.alter_column('waybills', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_waybills_order_id'), 'waybills', ['order_id'], unique=True)
    op.create_foreign_key(op.f('fk_waybills_order_id_orders'), 'waybills', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_waybills_order_id_orders'), 'waybills', type_='foreignkey')
    op.drop_index(op.f('ix_waybills_order_id'), table_name='waybills')
    op.alter_column('waybills', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('waybills', 'order_id')
    # ### end Alembic commands ###
