"""user: drop fields

Revision ID: fc4cd58848aa
Revises: a577e5a38788
Create Date: 2025-07-21 19:51:11.561630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4cd58848aa'
down_revision: Union[str, None] = 'a577e5a38788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('note', sa.String(), nullable=True))
    op.drop_column('users', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'note')
    # ### end Alembic commands ###
