name: deploy

permissions:
  contents: read
  security-events: write

on:
  push:
    tags:
      - '*'

env:
 APP_NAME: "be-tcf"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push Docker image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ env.APP_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ env.APP_NAME }}:latest
        format: 'sarif'
        exit-code: 0  # let the pipeline continue even if issues are found
        severity: 'CRITICAL,HIGH'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    name: Deploy to Kubernetes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Create kubeconfig directory
      run: |
        mkdir -p $HOME/.kube

    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy with Helm
      run: |
        helm upgrade --install ${{ env.APP_NAME }} ./chart \
          --namespace dev \
          --values chart/values.yaml
