name: test
on: [ push, pull_request ]

jobs:
  uv-setup:
    name: "tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6.3.1

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests
        run: |
          uv run pytest
